/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-18 23:50:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1576673378000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1576673378000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<title>NOTYET_SITE_TITLE</title>\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- slick -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("<!-- bx slider -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.   css\">\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- 헤더  -->\n");
      out.write("<header id=\"header\" class=\"header_main\">\n");
      out.write("\n");
      out.write("<!-- 두번째 헤더 -->\n");
      out.write("    <div class=\"sec_haed\">\n");
      out.write("\t    <!-- 고정헤더 -->\n");
      out.write("\t    <nav id=\"topUtil\" class=\"top_util\">\n");
      out.write("\t        <span>PIXAR</span>\n");
      out.write("\t        <ul class=\"nav\">\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLoginCheck\" id=\"login_btn\">로그인</a>        \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\" id=\"sign_btn\">회원가입</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"#\" id=\"mypage_btn\">마이페이지</a>   \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"#\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t        </ul>\n");
      out.write("\t    </nav>\n");
      out.write("\t<!-- 고정헤더 끝 -->\n");
      out.write("        <nav id=\"secUtil\" class=\"sec_util\">\n");
      out.write("            \n");
      out.write("            <span>\n");
      out.write("                <a href=\"#\">logo</a>\n");
      out.write("            </span>\n");
      out.write("                \n");
      out.write("            <ul class=\"nav-sec\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">예매</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">영화</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/theater/theaterInfo\">영화관</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">이벤트</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">스토어</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">VOD</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("    </div><!--div.sec_haed-->\n");
      out.write("    <!-- 두번째 헤더 끝 -->\n");
      out.write("</header>\n");
      out.write("<!-- 헤더 끝 -->\n");
      out.write("\n");
      out.write("<section id=\"content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 본문시작 -->\n");
      out.write("<div class=\"container\">\n");
      out.write("<!-- 슬릭슬라이드1 -->\n");
      out.write("     <section class=\"visual\">\n");
      out.write("         <div class=\"r\"> <img class=\"img\" src=\"img/몬스터호텔.jpg\" alt=\"\"> </div>\n");
      out.write("         <div class=\"r\"> <img class=\"img\" src=\"img/도리.jpg\" alt=\"\"> </div>\n");
      out.write("         <div class=\"r\"> <img class=\"img\" src=\"img/코코.jpg\" alt=\"\"> </div>\n");
      out.write("         <div class=\"r\"> <img class=\"img\" src=\"img/토이스토리.jpg\" alt=\"\"> </div>\n");
      out.write("    </section> \n");
      out.write("    \n");
      out.write("    <div class=\"deco\"></div><!--구분자-->\n");
      out.write("\n");
      out.write("<!-- bx 슬라이더2 -->\n");
      out.write("    <div class=\"slider\">\n");
      out.write("        <div>\n");
      out.write("            <img src=\"./img/M토이스토리4.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M업.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M인사이드아웃.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M인크레더블.PNG\" alt=\"\">\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("            <img src=\"./img/M코코.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M몬스터대학교.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M라따뚜이.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M코코.PNG\" alt=\"\">\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("            <img src=\"./img/M인사이드아웃.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M코코.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M토이스토리4.PNG\" alt=\"\">\n");
      out.write("            <img src=\"./img/M월E.PNG\" alt=\"\">\n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("    </div><!--div.slider--> \n");
      out.write("<!-- bx 슬라이더 2끝  -->\n");
      out.write("\n");
      out.write("    <div class=\"deco2\"></div><!--구분자-->\n");
      out.write("            \n");
      out.write("    <!-- 이벤트 -->\n");
      out.write("    <div class=\"con_fig\">\n");
      out.write("        <!-- 이벤트 좌측 -->\n");
      out.write("        <div class=\"con_event\">\n");
      out.write("            <span class=\"square\"></span>\n");
      out.write("            <h3>EVENT</h3>\n");
      out.write("            <button>당첨자발표</button>\n");
      out.write("        </div><!--div.con_event-->\n");
      out.write("        <!-- 이벤트 좌측 끝 -->\n");
      out.write("\n");
      out.write("    <!--이벤트 배너  -->\n");
      out.write("    <figure class=\"snip1283\">\n");
      out.write("        <img src=\"/img/E2.PNG\" alt=\"sample70\"/>\n");
      out.write("            <figcaption>\n");
      out.write("                <h3>통신사 할인</h3>\n");
      out.write("                <p>[할인]LG U+ 제휴된 통신사로 VIP 30% 할인 GOLD 15% Silver 10% 혜택을 지금 누리세요!</p><a href=\"#\" class=\"read-more\">Read More</a>\n");
      out.write("            </figcaption>\n");
      out.write("    </figure>\n");
      out.write("\n");
      out.write("    <figure class=\"snip1283 hover\">\n");
      out.write("        <img src=\"/img/E2.PNG\" alt=\"sample71\"/>\n");
      out.write("        <figcaption>\n");
      out.write("            <h3>마지막주 수요일 할인</h3>\n");
      out.write("            <p>[할인]매월 마지막주 수요일은 문화의 날 할인! 모든 영화를 5000원에 관람하세요!</p><a href=\"#\" class=\"read-more\">Read More</a>\n");
      out.write("        </figcaption>\n");
      out.write("    </figure>\n");
      out.write("    <figure class=\"snip1283\">\n");
      out.write("        <img src=\"/img/E2.PNG\" alt=\"sample76\"/>\n");
      out.write("            <figcaption>\n");
      out.write("                <h3>더블 포인트 적립</h3>\n");
      out.write("                <p>[적립]2020/01/01~2020/12/31 PIXAR 전용관 홍보하고 포인트 적립 2배로 받는 방법!</p><a href=\"#\" class=\"read-more\">Read More</a>\n");
      out.write("            </figcaption>\n");
      out.write("    </figure>\n");
      out.write("    </div><!--div con_fig-->\n");
      out.write("</div><!--div.container-->\n");
      out.write("            \n");
      out.write("<!--슬릭슬라이드1 스크립트  -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $('.visual').slick();\n");
      out.write("</script>   \n");
      out.write("<!-- bx슬라이더2  -->\n");
      out.write("<script>\n");
      out.write("$(document).ready(function(){\n");
      out.write("    $('.slider').bxSlider();\n");
      out.write("});\n");
      out.write("// evnet hover\n");
      out.write("$(\".hover\").mouseleave(\n");
      out.write("    function () {\n");
      out.write("      $(this).removeClass(\"hover\");\n");
      out.write("    }\n");
      out.write("  );\n");
      out.write("</script>   \n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("\n");
      out.write("<!-- slick -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("<!-- bx slider -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.   css\">\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("<!-- 풋터 -->\n");
      out.write("<footer class=\"foot\">\n");
      out.write("    <nav id=bottomFoot class=\"bottom_foot\">\n");
      out.write("        <ul class=\"nav-bottomfoot\">\n");
      out.write("            <li >\n");
      out.write("                <a href=\"\">공지사항\n");
      out.write("            </li>\n");
      out.write("            <li >\n");
      out.write("                <a href=\"#\">고객센터\n");
      out.write("            </li>\n");
      out.write("            <li >\n");
      out.write("                <a href=\"#\">이용약관\n");
      out.write("            </li>\n");
      out.write("            <li >\n");
      out.write("                <a href=\"#\">이벤트\n");
      out.write("            </li>\n");
      out.write("            <li >\n");
      out.write("                <a href=\"#\">스토어바로가기\n");
      out.write("            </li>\n");
      out.write("        </ul>           \n");
      out.write("    </nav>\n");
      out.write("        \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- 풋터 안 인포메이션 -->\n");
      out.write("    <div id=\"infoFoot\" class=\"info_foot\">\n");
      out.write("                                \n");
      out.write("        <span>사업자정보확인</span> <span>개인정보관리자</span><span>통신판매 신고번호 제 00000123123호</span> <br><br>\n");
      out.write("        <span>대표이사: NONAME</span> <span>본점: 서울특별시 서초구 서초동 123-456</span> <span>사업장: 서울특별시 마포구 상암로 123 상암동 456</span><br><br>\n");
      out.write("        <span>고객센터: 1234-5678</span> <span>NOTITLE문의: 02-1234-5678</span> <span>NOTITLE문의:  csnotitle@notitle.com</span>\n");
      out.write("        \n");
      out.write("    <h3>LOGO</h3>\n");
      out.write("    </div><!-- div.info_foot div-->\n");
      out.write("\n");
      out.write("    <div class=\"end_foot\">\n");
      out.write("        InsideOut\n");
      out.write("    </div><!--div.end_foot-->\n");
      out.write("    <!-- 풋터 안 인포메이션 끝 -->\n");
      out.write("</footer>\n");
      out.write("    <!-- 풋터 끝 -->   \n");
      out.write("            \n");
      out.write("            \n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
